targets:
  $default:
    builders:
      flutter_iconfont_generator:iconfont_builder:
        enabled: true
        generate_for:
          - lib/iconfont/**
          - lib/**/iconfont.dart
        options:
          # Only process files that match the iconfont pattern
          include: 
            - "lib/iconfont/**"
            - "lib/**/iconfont.dart"

builders:
  iconfont_builder:
    import: "package:flutter_iconfont_generator/builder.dart"
    builder_factories: ["iconFontBuilder"]
    build_extensions: {".dart": [".iconfont.g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["flutter_iconfont_generator:iconfont_builder"]
