name: flutter_iconfont_generator
description: A Dart/Flutter code generator for iconfont.cn icons.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  http: ^0.13.0
  xml: ^6.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  source_gen: ^1.2.0
  analyzer: ^5.0.0
  build: ^2.3.0
  yaml: ^3.1.0

# Iconfont configuration
iconfont:
  symbol_url: "//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js"
  save_dir: "./lib/iconfont"
  trim_icon_prefix: "icon"
  default_icon_size: 18
  null_safety: true

# Flutter configuration
flutter:
  uses-material-design: true

# Executable scripts
executables:
  iconfont_generator: iconfont_generator
