name: flutter_iconfont_generator
description: A Dart/Flutter code generator for iconfont.cn icons. Converts iconfont.cn icons to Flutter widgets with SVG rendering, supporting multi-color icons and null safety.
homepage: https://github.com/suyulin/flutter_iconfont_generator
repository: https://github.com/suyulin/flutter_iconfont_generator
issue_tracker: https://github.com/suyulin/flutter_iconfont_generator/issues

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  http: ^1.0.0
  xml: ^6.3.0
  path: ^1.8.3
  yaml: ^3.1.2
  build: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  source_gen: ^1.4.0
  analyzer: ^6.0.0

# Flutter configuration
flutter:
  uses-material-design: true

# Example iconfont configuration (for reference)
# Add this to your project's pubspec.yaml:
# iconfont:
#   symbol_url: "//at.alicdn.com/t/font_xxx.js"  # Replace with your iconfont.cn URL
#   save_dir: "./lib/iconfont"
#   trim_icon_prefix: "icon"
#   default_icon_size: 18
#   null_safety: true

# Executable scripts
executables:
  iconfont_generator: iconfont_generator
